# Generated by Django 5.1.6 on 2025-05-02 03:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('full_name', models.CharField(default='', max_length=150, verbose_name='Nombre y Apellido')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('nationality', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nacionalidad')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de habitación')),
                ('email', models.EmailField(max_length=255, verbose_name='Correo Electrónico')),
                ('phone_prefix', models.CharField(blank=True, max_length=4, null=True, verbose_name='Prefijo de Tlf (+58)')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono')),
                ('person_type', models.CharField(choices=[('N', 'NATURAL'), ('J', 'JURIDICO')], default='N', max_length=1, verbose_name='Tipo de Persona')),
                ('gender', models.CharField(choices=[('NA', 'NO APLICA'), ('M', 'HOMBRE'), ('F', 'MUJER')], max_length=2, verbose_name='Género')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': 'client',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted__isnull', False)), fields=('email', 'deleted'), name='clients_email_key')],
            },
        ),
    ]
