# Generated by Django 5.1.6 on 2025-05-01 21:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('description', models.CharField(max_length=150, verbose_name='Descripción')),
                ('minimum_payment', models.FloatField(verbose_name='Pago Mínimo')),
                ('maximum_payment', models.FloatField(verbose_name='Pago Máximo')),
                ('credit_period', models.PositiveIntegerField(verbose_name='Plazo de Crédito (Meses)')),
                ('credit_type', models.CharField(choices=[('A', 'Automotriz'), ('H', 'Hipotecarios'), ('C', 'Comerciales')], max_length=2, verbose_name='Tipo de Crédito')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'credit',
                'verbose_name_plural': 'credits',
                'db_table': 'credit',
            },
        ),
    ]
