# Generated by Django 5.1.6 on 2025-05-01 21:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('name', models.CharField(max_length=150, verbose_name='Descripción')),
                ('bank_type', models.CharField(choices=[('P', 'Privado'), ('G', 'Gobierno')], max_length=2, verbose_name='Tipo de Banco')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'bank',
                'verbose_name_plural': 'banks',
                'db_table': 'bank',
            },
        ),
    ]
